Back-end (Emakers)/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index

# URLs das telas de login, logout e index
urlpatterns = [
    path('', index, name='index'),
    path('index/', index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

Back-end (Emakers)/ginca_web/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include
)

# URLs bases do sistema
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('scoremanager.urls')),
]

Back-end (Emakers)/scoremanager/urls.py
from django.urls import path
from .views import (
    list_events,
	apply_bonus,
	apply_penalty,
	list_ranking
)

# URLs de bonificação e penalidade, ranking e eventos
urlpatterns = [
    path('bonus/<int:id_user>/', apply_bonus, name='url_bonus'),
    path('penalty/<int:id_user>/',apply_penalty, name='url_penalty'),
    path('ranking/', list_ranking, name='url_ranking'),
    path('events/', list_events, name='url_events')
]

Back-end (Emakers)/scoremanager/models.py
from django.db import models
from users.models import User
from datetime import datetime

# Modelo da tabela Score
class Score(models.Model):
    type_score = models.CharField('Tipo', max_length=5)
    score_description = models.TextField('Descrição', max_length=255)
    equivalent_score = models.IntegerField('Equivalência')
    
    BONUS = 'B'
    PENALTY = 'P'
    SCORE_CHOICES = [
        (BONUS, 'Bônus'),
        (PENALTY, 'Penalidade'),
    ]
    score_specification = models.CharField(verbose_name='Specification', max_length=1, choices=SCORE_CHOICES, default=BONUS)

    class Meta:
        verbose_name = 'Pontuação'
        verbose_name_plural = 'Pontuações'

    def __str__(self):
        return self.type_score

    def __add__(self, other_score):
        return self.equivalent_score + other_score.equivalent_score

# Modelo da tabela User_has_score
class User_has_score(models.Model):
    user = models.ForeignKey(User, verbose_name='Usuário', related_name='user_has_scores', on_delete=models.CASCADE)
    score = models.ForeignKey(Score, verbose_name='Pontuação', related_name='users_has_score', on_delete=models.PROTECT)
    score_comment = models.TextField('Comentário', max_length=255)
    score_date = models.DateTimeField(default=datetime.now)
    admin_username = models.CharField(verbose_name='Nome', max_length=100, default="")

    class Meta:
        verbose_name = 'Pontuação Usuário'
        verbose_name_plural = 'Pontuações Usuários'

    def __str__(self):
        return self.user.username + " - " + self.score.type_score

Back-end (Emakers)/scoremanager/forms.py
from django import forms
from .models import (
	Score,
	User_has_score
)

# Formulário de pontuação, pode ser penalidade ou bônus
class Score_Form(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['type_score', 'score_description', 'equivalent_score', 'score_specification']

    # Função que salva a pontuação no banco de dados
    def save(self, commit=True):
        score = super().save(commit=False)
        if commit:
            score.save()
        return score

# Formulário para aplicação de pontuação a um usuário específico
class Apply_Score_Form(forms.ModelForm):
	class Meta:
		model = User_has_score
		fields = ['user', 'score', 'score_comment', 'admin_username']

Back-end (Emakers)/scoremanager/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from operator import itemgetter
import json
from django.shortcuts import (
	render,
	redirect
)
from .forms import (
	Score_Form,
	Apply_Score_Form
)
from .models import (
	Score,
	User,
	User_has_score
)
from threading import Thread
import time
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header

# Função que envia email ao usuário penalizado
def email_sender(input_message, email_to):

    to = email_to
    gmail_user = 'gincaweb@gmail.com'
    gmail_pwd = 'gincaweb123'
    smtpserver = smtplib.SMTP("smtp.gmail.com",587)
    smtpserver.ehlo()
    smtpserver.starttls()
    smtpserver.ehlo
    smtpserver.login(gmail_user, gmail_pwd)
    header = 'To:' + to + '\n' + 'From: ' + gmail_user + '\n' + 'Subject:Penalidade recebida! \n'
    input_message = input_message
    msg = header + input_message 
    smtpserver.sendmail(gmail_user, to, msg)
    smtpserver.close()

# Função que retorna o ranking de todos os usuários
def get_ranking():
	users = User.objects.all()
	total_score_users = {}
	for user in users:
		sum_score_user = 0
		for user_has_score in user.user_has_scores.all():
			sum_score_user += user_has_score.score.equivalent_score
		total_score_users[user.username] = sum_score_user

	ranking = sorted(total_score_users.items(), key=itemgetter(1), reverse=True)

	return ranking

@login_required
def list_ranking(request):
	ranking = get_ranking()
	return render(request, 'ranking.html', {'ranking': ranking})

# Função para aplicar bonificação a um usuário, só pode ser chamada por um administrador
@login_required
def apply_bonus(request, id_user):
	if request.user.is_superuser:
		userAux = User.objects.get(pk=id_user)
		form = Apply_Score_Form(request.POST)
		scores = Score.objects.filter(score_specification='B')

		if request.POST:
			mutable = request.POST._mutable
			request.POST._mutable = True
			score_data = json.loads(form.data['score'])
			form.data['score'] = score_data['score_id']
			request.POST._mutable = mutable

		if form.is_valid():
			form.save()
			return redirect('url_participants')

		return render(request, 'apply-bonus.html', {'form': form, 'userAux': userAux, 'scores': scores})
	else:
		return HttpResponseNotFound()

# Função que aplica penalidade a um usuário, só pode ser chamada por um administrador
@login_required
def apply_penalty(request, id_user):
    if request.user.is_superuser:
        userAux = User.objects.get(pk=id_user)
        form = Apply_Score_Form(request.POST)
        scores = Score.objects.filter(score_specification='P')

        if request.POST:
            mutable = request.POST._mutable
            request.POST._mutable = True
            score_data = json.loads(form.data['score'])
            form.data['score'] = score_data['score_id']
            request.POST._mutable = mutable

        if form.is_valid():
            form.save()
            email_sender(form.data['score_comment'], userAux.email)
            return redirect('url_participants')

        return render(request, 'apply-penalty.html', {'form': form, 'userAux': userAux, 'scores': scores})
    else:
        return HttpResponseNotFound()

# Função que lista os eventos
@login_required
def list_events(request):
    # Se o usuário for administrador: lista todos eventos
    # Senão: lista somente os eventos relacionados a ele
    if request.user.is_superuser:
        events_list = User_has_score.objects.all()
    else:  
        events_list = User_has_score.objects.filter(user=request.user)
     
    paginator = Paginator(events_list, 9)

    page = request.GET.get('page')
    events = paginator.get_page(page)

    return render(request, 'events.html', {'events': events})

Back-end (Emakers)/scoremanager/templates/apply-bonus.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<form method="POST"> 
{% csrf_token %}
<div id="bonificar" class="tabcontent">
    <div class="bonificarContent">
        <div class="bonificarBody">
        <div class="bonificar-title">
            <h1>BONIFICAR</h1>
        </div>
        <input name="user" id="id_user" value="{{userAux.id}}" type="hidden">
        <div class="bonificar-select">
            <select name="score" required id="id_score" onChange="changeScore">
            {% for score in scores %}
                <option value='{"score_id":"{{score.id}}","equivalent_score":"{{score.equivalent_score}}"}'>{{score.type_score}} - {{score.score_description}}</option>
            {% endfor %}
            </select>
        </div>
        <div class="bonificar-pontos">
            <h3>{{userAux.username}} receberá uma bonificação de {% if scores %} <span value="{{score.id}}" id="print_equivalent_score"></span> {% else %} 0 {% endif %} pontos</h3>
        </div>
        <div class="bonificar-message" >
            <input type="text" placeholder="Adicione comentários aqui..." required id="id_score_comment" name="score_comment">
        </div>
        <input type="hidden" name="admin_username" maxlength="100" value="{{user.username}}" id="id_admin_username">
        <div class="bonificar-buttons">
            <div class="bonificar-cancel">
                <button onclick="location.href={% url 'url_participants' %}">CANCELAR</button>
            </div>
            <div class="bonificar-confirm">
                <button type="submit">CONFIRMAR</button>
            </div>
        </div>
        </div>
        
    </div>
    </div>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
    <script>
      function changeScore() {
        var score_data = $.parseJSON($('#id_score option:selected').val()); // armazendando em variavel
        document.getElementById("print_equivalent_score").innerHTML = score_data['equivalent_score'];
      }
      $( document ).ready(function() {
          $( window ).on('change', changeScore);
          $( window ).on('load', changeScore);
      });
    </script>
{% endif %}
{% endblock content %}

Back-end (Emakers)/scoremanager/templates/apply-penalty.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<form method="POST"> 
{% csrf_token %}
<div id="penalizar" class="tabcontent">
    <div class="penalizarContent">
        <div class="penalizarBody">
        <div class="penalizar-title">
            <h1>PENALIZAR</h1>
        </div>
        <input name="user" id="id_user" value="{{userAux.id}}" type="hidden">
        <div class="penalizar-select">
            <select name="score" required id="id_score">
            {% for score in scores %}
                <option value='{"score_id":"{{score.id}}","equivalent_score":"{{score.equivalent_score}}"}'>{{score.type_score}} - {{score.score_description}}</option>
            {% endfor %}
            </select>
        </div>
        <div class="penalizar-pontos">
            <h3>{{userAux.username}} receberá uma penalização de {% if scores %} <span value="{{score.id}}" id="print_equivalent_score"></span> {% else %} 0 {% endif %} pontos</h3>
        </div>
        <div class="penalizar-message">
            <input type="text" placeholder="Adicione comentários aqui..." id="id_score_comment" required name="score_comment">
        </div>
        <input type="hidden" name="admin_username" maxlength="100" value="{{user.username}}" id="id_admin_username">
        <div class="penalizar-buttons">
            <div class="penalizar-cancel">
                <button onclick="location.href={% url 'url_participants' %}">CANCELAR</button>
            </div>
            <div class="penalizar-confirm">
                <button type="submit">CONFIRMAR</button>
            </div>
        </div>
       
        </div>
    </div>
    </div>
    </div>
</div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
    <script>
      function changeScore() {
        var score_data = $.parseJSON($('#id_score option:selected').val()); // armazendando em variavel
        document.getElementById("print_equivalent_score").innerHTML = score_data['equivalent_score'];
      }
      $( document ).ready(function() {
          $( window ).on('change', changeScore);
          $( window ).on('load', changeScore);
      });
</script>
{% endif %}
{% endblock content %}

Back-end (Emakers)/scoremanager/templates/events.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div id="eventos" class="tabcontent">
  <div class="eventosContent">
    <div class="eventosBody">
      <div class="eventos-container">
        <div class="eventos-top">
          <h2>REGISTRO DE EVENTOS</h2>
        </div>
        <div class="eventos-bottom">
          
          <div class="eventos-tablecontent">
            <table>
              <thead>
                <tr class="eventos-tablehead">
                  <th>Responsável</th>
                  <th>Ação</th>
                  <th>Participante</th>
                  <th>Data</th>
                  <th>Razão</th>
                </tr>
              </thead>
              <tbody class="table-body-bottom">
                {% for event in events %}
                <tr>
                  <td>{{event.admin_username}}</td>
                  <td>{{event.score.equivalent_score}}</td>
                  <td>{{event.user.username}}</td>
                  <td>{{event.score_date}}</td>
                  <td>
                    <div class="table-icons">
                      <button type="button" id="btn-msg" class="btn-msg"><img src="{% static 'assets/razao.svg' %}"
                          alt=""></button>
                    </div>
                    <!--Conteudo do modal da mensagem de pontuacao-->
                    <div id="myModalMessage" class="event-modal">
                        <div class="event-modal-content">
                        <div class="event-modal-top">
                            <div class="event-modal-top-text">
                            <div class="event-modal-top-text-content">
                                <p>Mensagem da Pontuação</p>
                            </div>
                            </div>
                            <div class="event-modal-top-close">
                            <span class="close">&times;</span>
                            </div>
                        </div>
                        <div class="event-modal-bottom">
                            <div class="event-modal-bottom-field">
                            <p>{{event.score_comment}}</p>
                            </div>
                        </div>
                        </div>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="pagination">
          <span class="step-links">
            {% if events.has_previous %}
            
                <a href="?page={{ events.previous_page_number }}"> anterior</a>
            {% endif %}

            <span class="current">
              {{ events.number }} de {{ events.paginator.num_pages }}.
            </span>

            {% if events.has_next %}
            <a href="?page={{ events.next_page_number }}">proximo </a>
            {% endif %}
          </span>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  var modalMsg = document.getElementById("myModalMessage");
  var btnMsg = document.getElementById("btn-msg");
  var spanMsg = document.getElementsByClassName("close")[0];
  btnMsg.onclick = function () {
    modalMsg.style.display = "block";
  }
  spanMsg.onclick = function () {
    modalMsg.style.display = "none";
  }
  window.onclick = function (event) {
    if (event.target == modalMsg) {
      modalMsg.style.display = "none"
    }
  }
</script>
{% endif %}
{% endblock content %}

Back-end (Emakers)/scoremanager/templates/ranking.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
    <div id="ranck" class="tabcontent">
      <div class="ranckContent">
        <div class="ranckBody">
          <div class="ranck-container">
            <div class="ranck-top">
              <h2>RANKING</h2>
            </div>
            <div class="ranck-bottom">
            {% for username, total_score_user in ranking %}
              <div class="ranck-bottom-cell">
                <div class="ranck-bottom-text">
                  <h4>{{ forloop.counter }}º</h4>
                </div>
                <div class="ranck-bottom-text">
                  <h4>{{ total_score_user }}</h4>
                </div>
                <div class="ranck-bottom-cell-profile">
                  <div class="ranck-bottom-cell-profile-circle"></div>
                </div>
                <div class="ranck-bottom-text">
                  <h4>{{ username }}</h4>
                </div>
              </div>
            {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock content %}