Back-end (Emakers)/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index

# URLs das telas de login, logout e index
urlpatterns = [
    path('', index, name='index'),
    path('index/', index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

Back-end (Emakers)/ginca_web/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include
)

# URLs bases do sistema
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('scoremanager.urls')),
]

Back-end (Emakers)/users/urls.py
from django.urls import path
from .views import (
	profile_user,
	list_users
)

# URLs para a tela de participantes e para o perfil
urlpatterns = [
	path('participants/', list_users, name='url_participants'),
	path('my_profile/', profile_user, name='url_my_profile')
]

Back-end (Emakers)/scoremanager/models.py
from django.db import models
from users.models import User
from datetime import datetime

# Modelo da tabela Score
class Score(models.Model):
    type_score = models.CharField('Tipo', max_length=5)
    score_description = models.TextField('Descrição', max_length=255)
    equivalent_score = models.IntegerField('Equivalência')
    
    BONUS = 'B'
    PENALTY = 'P'
    SCORE_CHOICES = [
        (BONUS, 'Bônus'),
        (PENALTY, 'Penalidade'),
    ]
    score_specification = models.CharField(verbose_name='Specification', max_length=1, choices=SCORE_CHOICES, default=BONUS)

    class Meta:
        verbose_name = 'Pontuação'
        verbose_name_plural = 'Pontuações'

    def __str__(self):
        return self.type_score

    def __add__(self, other_score):
        return self.equivalent_score + other_score.equivalent_score

# Modelo da tabela User_has_score
class User_has_score(models.Model):
    user = models.ForeignKey(User, verbose_name='Usuário', related_name='user_has_scores', on_delete=models.CASCADE)
    score = models.ForeignKey(Score, verbose_name='Pontuação', related_name='users_has_score', on_delete=models.PROTECT)
    score_comment = models.TextField('Comentário', max_length=255)
    score_date = models.DateTimeField(default=datetime.now)
    admin_username = models.CharField(verbose_name='Nome', max_length=100, default="")

    class Meta:
        verbose_name = 'Pontuação Usuário'
        verbose_name_plural = 'Pontuações Usuários'

    def __str__(self):
        return self.user.username + " - " + self.score.type_score

Back-end (Emakers)/users/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, 
    AbstractBaseUser,
    PermissionsMixin
)

# Funções para criar o usuário comum e o administrador
class User_Manager(BaseUserManager):
    def create_user(self, username, email, date_of_birth, password=None):
        
        if not username:
            raise ValueError('Usuários precisam de um nome')

        if not email:
            raise ValueError('Usuários precisam de um email')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, email, date_of_birth, password):
        
        user = self.create_user(
            username,
            email,
            password=password,
            date_of_birth=date_of_birth,
        )

        user.is_superuser = True
        user.save(using=self._db)

        return user

# Modelo para criação da tabela User no banco de dados
class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(verbose_name='Nome', max_length=100, unique=True)
    email = models.EmailField(verbose_name='Email', max_length=255, unique=True)
    date_of_birth = models.DateField(verbose_name='Data de Nascimento')
    is_active = models.BooleanField(verbose_name='Ativo', default=True)
    
    MALE = 'M'
    FEMALE = 'F'
    SEX_CHOICES = [
    	(MALE, 'Masculino'),
    	(FEMALE, 'Feminino'),
    ]
    sex = models.CharField(verbose_name='Sexo', max_length=1, choices=SEX_CHOICES, default=MALE)
    
    objects = User_Manager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'date_of_birth']

    class Meta:
        verbose_name='Usuário'

    def __str__(self):
        return self.username

Back-end (Emakers)/users/forms.py
from django import forms
from .models import	User

# Formulário que valida e salva a senha do usuário
class User_Creation_Form(forms.ModelForm):
    
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação da senha', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'date_of_birth', 'sex')

    def clean_password2(self):
        # Confirma se as senhas conferem
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("As senhas não correspondem")
            
        return password2

    def save(self, commit=True):
        # Criptografa a senha como hash e salva no banco
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()

        return user

# Formulário para alteração dos dados do usuário
class User_Change_Form(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'date_of_birth', 'password')

    def save(self, commit=True):
        # Criptografa a senha como hash e salva no banco
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()
            
        return user

Back-end (Emakers)/users/views.py
from django.http import HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from .models import User
from scoremanager.models import Score
from django.shortcuts import (
	render,
	redirect	
)
from django.http import HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import register
from .forms import (
	User_Creation_Form,
	User_Change_Form
)
from scoremanager.forms import (
    Score_Form,
	Apply_Score_Form
)
from .models import User
from scoremanager.models import Score
from scoremanager.views import get_ranking


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

# Lista todos os usuários cadastrados no sistema
@login_required
def list_users(request):
    if request.user.is_superuser:
        users = User.objects.all().order_by('username')
        form = User_Creation_Form(request.POST or None)
        score = Score_Form(request.POST or None)
        ranking = dict(get_ranking())

        if form.is_valid():
            form.save()
            return redirect('url_participants')

        if score.is_valid():
            score.save()
            return redirect('url_participants')

        return render(request, 'participants.html', {'users': users, 'form': form, 'score': score, 'ranking': ranking})
    else:
        return HttpResponseNotFound()

# Exibe o perfil do usuário e permite edição
@login_required
def profile_user(request):
    userAtual = User.objects.get(pk=request.user.id)
    form = User_Change_Form(request.POST or None, instance=userAtual)

    if form.is_valid():
        form.save()
        return redirect('index')

    return render(request, 'profile.html', {'userAtual': userAtual, 'form': form})

Back-end (Emakers)/users/templates/participants.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
    <div id="participante" class="tabcontent">
      <div class="participanteContent">
        <div class="participanteBody">
          <div class="participante-Buttons">
            <button type="button" id="btn-user" class="btn-user">
              <img src="{% static 'assets/membros_add.svg' %}" width="15px"> 
              Cadastrar Usuário
            </button>
            <button type="button" id="btn-score" class="btn-score">
              <img src="{% static 'assets/caixa_add_quadrada.svg' %}" width="15px"> 
              Cadastrar Pontuação
            </button>
          </div>
          <div class="participante-table">
            <div class="table-title">
              <h3>PARTICIPANTES</h3>
            </div>
            <div class="table-content">
                
              <!-- Conteudo do Modal adcionar Usuario -->
          
              <form method="POST"> 
              {% csrf_token %}
              <div id="myModalUser" class="modal">
                <div class="modal-content">
                  <div class="modal-top">
                    <div class="modal-top-text">
                        <div class="modal-top-text-content">
                          <p>Cadastrar novo usuário</p>
                        </div>
                    </div>
                    <div class="modal-top-close">
                        <span class="close">&times;</span>
                    </div>
                  </div>
                  <div class="modal-bottom">
                    <div class="modal-bottom-field">
                        <p>Nome:</p>
                        <input type="text" placeholder="Digite o nome do participante" name="username" maxlength="100" required id="id_username">
                    </div>
                    <div class="modal-bottom-field">
                        <p>Email:</p>
                        <input type="email" name="email" maxlength="255" required id="id_email" placeholder="Digite o email do participante">
                    </div>
                    <div class="modal-bottom-field">
                        <p>Data de Nascimento:</p>
                        <input type="date" name="date_of_birth" required id="id_date_of_birth">
                    </div>
                    <div class="modal-bottom-field">
                        <p>Sexo</p>
                        <div class="modal-bottom-row">
                          <select name="sex" id="id_sex">
                            <option value="M" selected>Masculino</option>

                            <option value="F">Feminino</option>
                          </select>
                        </div>
                    </div>
                    <div class="modal-bottom-field">
                        <p> Senha: </p>
                          <input type="password" name="password1" required id="id_password1">
                        <p> Confirmação da senha: </p> 
                          <input type="password" name="password2" required id="id_password2">
                          <button type="submit">Salvar</button> 
                    </div>
                  </div>
                </div>
              </form>
            </div>
                    
            <!-- Conteudo do Modal adcionar Pontuação -->
            <form method="POST"> 
            {% csrf_token %}
            <div id="myModalScore" class="modal">
              <div class="modal-content">
                <div class="modal-top">
                  <div class="modal-top-text">
                      <div class="modal-top-text-content">
                      <p>Cadastrar nova pontuação</p>
                      </div>
                  </div>
                  <div class="modal-top-close">
                      <span class="close">&times;</span>
                  </div>
                </div>
                <div class="modal-bottom">
                <div class="modal-bottom-field">
                  <p>Tipo</p>
                  <input type="text" name="type_score" placeholder="Digite o tipo da pontuação (Ex.B07, P14)" id="id_type_score">
                </div>
                <div class="modal-bottom-field">
                  <p>Descrição</p>
                  <textarea rows="4" cols="60" name="score_description" placeholder="Descreva a pontuação (Ex.: O membro teve imprevistos)" id="id_score_description"></textarea>
                </div>
                <div class="modal-bottom-field">
                  <p>Selecione:<p>
                  <select name="score_specification" id="id_score_specification">
                    <option value="B" selected>Bônus</option>

                    <option value="P">Penalidade</option>
                  </select>
                </div>
                <div class="modal-bottom-field">
                  <p>Pontos</p>
                  <input type="number" name="equivalent_score" required id="id_equivalent_score">
                </div>
                <div class="modal-bottom-field">
                  <button id="btn-save" type="submit">Salvar</button>
                </div>
              </div>
            </div>
          </div>
          </form>
          <div class="table-content-field">
            <table id="table">
              <thead>
                <tr class="content-title">
                  <th>
                    <div class="row-table">
                      <div class="row-table-check">
                        <input type="checkbox" id="check-all">
                        <label id="checklabel" for="check-all"></label>
                      </div>
                      <div class="row-table-content">
                        <h4>Nome</h4>
                        <img src="{% static 'assets/ordenar_alfabeto.svg' %}" width="18px">
                      </div> 
                    </div>
                  </th>
                  <th>Email<img src="{% static 'assets/ordenar_alfabeto.svg' %}" width="18px"></th>
                  <th>Pontos<img src="{% static 'assets/ordenar.svg' %}" width="18px"></th>
                  <th>Opções</th>
                </tr>
              </thead>
              <tbody>
              {% for user in users %}
                <tr>
                <td>
                  <div class="row-table">
                    <div class="row-table-check">
                      <input type="checkbox" id="name03">
                      <label for="name03"></label>
                    </div>
                    <div class="row-table-content">
                      <h5>{{ user.username }}</h5>
                    </div>
                  </div>
                </td>
                <td>{{ user.email }}</td>
                <td>{{ ranking|get_item:user.username }}</td>
                <td>
                  <div class="row-table-option">
                    <img onclick="location.href='/bonus/{{user.id}}'" src="{% static 'assets/caixa_add_redonda.svg' %}">
                    <img onclick="location.href='/penalty/{{user.id}}'" src="{% static 'assets/caixa_remove_redonda.svg' %}">
                    <img src="{% static 'assets/configuracoes.svg' %}">
                  </div>
                </td>
                </tr>
              {% endfor %}
                    
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

Back-end (Emakers)/users/templates/profile.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
    <form method="POST" action=""> 
    {% csrf_token %}
      <div class="content">
        <div class="profile-body">          
          <div class="profile-content">
            <div class="profile-img-content">                
              <div class="img-profile">
                <img src="{% static 'assets/foto_jovem.svg' %}" alt="">
              </div>
              <div class="profile-button">
                <label for="img">Alterar foto</label>
                <input type="file" name="" id="img">
              </div>
            </div>

            <div class="profile-info-content">
              <div class="form-group">
              {% for field in form %}                         
              <div class="row">
                <label for="{{ field.id_for_label }}"></label>
                {% if field.id_for_label != 'id_password' %}
                  {% render_field field class="form-control" placeholder=field.label %}
                {% else %}
                  <input type="password" name="password" placeholder="Digite a nova senha" required id="id_password">
                {% endif %}
                <img src="{% static 'assets/caneta_edit.svg' %}" alt="">                  
              </div>
              <div class="{% if field.errors %} invalid {% endif %}">
                {% for error in field.errors %}
                  <p class="help-block">{{ error }}</p>
                {% endfor %}
              </div>
              {% endfor %}
              <div class="row">
                <button type="button" class="profile-info-cancel" onclick="location.href={% url 'index' %}">Cancelar</button>
                <button type="submit"class="profile-info-confirm">Confirmar</button>
              </div>
             </div>
            </div>

            <div class="profile-logo-content">
              <img src="{% static 'assets/Logo_completa_secundaria_semfundo.png' %}" alt="">
            </div>
          </form>
        </div>          
      </div>    
     </div>
   </div>
  {% endif %}
{% endblock content %}